### PR TITLE
Update ProgressIndicator.java

### PR DESCRIPTION
**Pull request by johncblandii**
package name was wrong in java file.

### CODE REVIEW

**Comment by johncblandii** [comment]
Thanks @saaksshi.

**Comment by saaksshi** [comment]
@johncblandii WC

**Comment by saaksshi** [comment]
It has 1 more mistake in iOS I'll update it today.
then you can merge it.

**Comment by johncblandii** [comment]
That works for me. Tag me when you do.

**Comment by saaksshi** [comment]
Hi I have updated iOS code also.
Please have a look @ it.

On Thu, Aug 13, 2015 at 1:23 PM, John C. Bland II notifications@github.com
wrote:

> That works for me. Tag me when you do.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/johncblandii/cordova-progressIndicator/pull/1#issuecomment-130568158
> .

## 

Regards,
Saaksshi Tyagi https://in.linkedin.com/in/saaksshityagi

**Pull request merged**
